name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DamianReeves/write-file-action@master
        with:
          path: ./API_KEYS
          contents: |
            APP_ID = 6
            APP_HASH = "eb06d4abfb49dc3eeb1aeb98ae0f581e"
            MAPS_V2_API = somekey
          write-mode: overwrite

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleAfatRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-unsigned
          path: TMessagesProj/build/outputs/apk/afat/release/*.apk
